## 5.1 Atomic Vectors

## 5.2 Attributes

### Names

In [13]:
die <- 1:6
attributes(die)

NULL

Most common attributes given to vectors are:
- names
- dimensions
- classes

In [14]:
names(die) <- c("one", "two", "three", "four", "five", "six")

In [15]:
names(die)

[1] "one"   "two"   "three" "four"  "five"  "six"

In [16]:
attributes(die)

$names
[1] "one"   "two"   "three" "four"  "five"  "six"

In [17]:
die

one   two three  four  five   six 
    1     2     3     4     5     6

In [18]:
names(die) <- NULL
die

[1] 1 2 3 4 5 6

### Dim

In [21]:
dim(die) <- c(2, 3)
die

[,1] [,2] [,3]
[1,] 1    3    5   
[2,] 2    4    6

In [24]:
dim(die) <- c(1, 2, 3)
die

, , 1

     [,1] [,2]
[1,]    1    2

, , 2

     [,1] [,2]
[1,]    3    4

, , 3

     [,1] [,2]
[1,]    5    6

## 5.3 Matrices

In [28]:
m <- matrix(die, nrow=2, byrow=TRUE)
m

[,1] [,2] [,3]
[1,] 1    2    3   
[2,] 4    5    6

## 5.4 Arrays

In [31]:
cards <- c("ace", "king", "queen", "jack", "ten", "spades", "spades", "spades", "spades", "spades")
m <- matrix(cards, ncol=2)
m
            

[,1]  [,2]  
[1,] ace   spades
[2,] king  spades
[3,] queen spades
[4,] jack  spades
[5,] ten   spades

## 5.5 Class

In [33]:
die <- 1:6
dim(die) <- c(2, 3)
typeof(die)

[1] "integer"

In [34]:
class(die)

[1] "matrix" "array"

In [35]:
attributes(die)

$dim
[1] 2 3

### Dates and times

In [37]:
now <- Sys.time()
now

[1] "2022-01-10 17:22:16 EST"

In [38]:
typeof(now)

[1] "double"

In [39]:
class(now)

[1] "POSIXct" "POSIXt"

In [40]:
unclass(now)

[1] 1641853337

### Factors

If you've programmed in other languages before, **factors** are R's version of **enums**.

In [41]:
gender <- factor(c("male", "female", "female", "male"))

In [42]:
typeof(gender)

[1] "integer"

In [45]:
print(attributes(gender))

$levels
[1] "female" "male"  

$class
[1] "factor"



In [47]:
print(unclass(gender))

[1] 2 1 1 2
attr(,"levels")
[1] "female" "male"  


In [48]:
print(gender)

[1] male   female female male  
Levels: female male
