## 5.1 Atomic Vectors

## 5.2 Attributes

### Names

In [13]:
die <- 1:6
attributes(die)

NULL

Most common attributes given to vectors are:
- names
- dimensions
- classes

In [14]:
names(die) <- c("one", "two", "three", "four", "five", "six")

In [15]:
names(die)

[1] "one"   "two"   "three" "four"  "five"  "six"

In [16]:
attributes(die)

$names
[1] "one"   "two"   "three" "four"  "five"  "six"

In [17]:
die

one   two three  four  five   six 
    1     2     3     4     5     6

In [18]:
names(die) <- NULL
die

[1] 1 2 3 4 5 6

### Dim

In [21]:
dim(die) <- c(2, 3)
die

[,1] [,2] [,3]
[1,] 1    3    5   
[2,] 2    4    6

In [24]:
dim(die) <- c(1, 2, 3)
die

, , 1

     [,1] [,2]
[1,]    1    2

, , 2

     [,1] [,2]
[1,]    3    4

, , 3

     [,1] [,2]
[1,]    5    6

## 5.3 Matrices

In [28]:
m <- matrix(die, nrow=2, byrow=TRUE)
m

[,1] [,2] [,3]
[1,] 1    2    3   
[2,] 4    5    6

## 5.4 Arrays

In [31]:
cards <- c("ace", "king", "queen", "jack", "ten", "spades", "spades", "spades", "spades", "spades")
m <- matrix(cards, ncol=2)
m
            

[,1]  [,2]  
[1,] ace   spades
[2,] king  spades
[3,] queen spades
[4,] jack  spades
[5,] ten   spades

## 5.5 Class

In [33]:
die <- 1:6
dim(die) <- c(2, 3)
typeof(die)

[1] "integer"

In [34]:
class(die)

[1] "matrix" "array"

In [35]:
attributes(die)

$dim
[1] 2 3

### Dates and times

In [37]:
now <- Sys.time()
now

[1] "2022-01-10 17:22:16 EST"

In [38]:
typeof(now)

[1] "double"

In [39]:
class(now)

[1] "POSIXct" "POSIXt"

In [40]:
unclass(now)

[1] 1641853337

### Factors

If you've programmed in other languages before, **factors** are R's version of **enums**.

In [41]:
gender <- factor(c("male", "female", "female", "male"))

In [42]:
typeof(gender)

[1] "integer"

In [45]:
print(attributes(gender))

$levels
[1] "female" "male"  

$class
[1] "factor"



In [47]:
print(unclass(gender))

[1] 2 1 1 2
attr(,"levels")
[1] "female" "male"  


In [48]:
print(gender)

[1] male   female female male  
Levels: female male


## 5.6 Coercion

In [1]:
as.character(TRUE)

[1] "TRUE"

## 5.7 Lists

In [3]:
card <- list("ace", "hearts", 1)
print(card)

[[1]]
[1] "ace"

[[2]]
[1] "hearts"

[[3]]
[1] 1



## 5.8 Data frame

In [4]:
df <- data.frame(
    face=c("ace", "two", "six"),
    suit=c("clubs", "clubs", "clubs"),
    value=c(1, 2, 3),
    stringsAsFactors=FALSE)

In [5]:
df

face suit  value
1 ace  clubs 1    
2 two  clubs 2    
3 six  clubs 3

## 5.9 Load data

In [9]:
deck <- read.csv("./deck.csv")
deck

face  suit     value
1  king  spades   13   
2  queen spades   12   
3  jack  spades   11   
4  ten   spades   10   
5  nine  spades    9   
6  eight spades    8   
7  seven spades    7   
8  six   spades    6   
9  five  spades    5   
10 four  spades    4   
11 three spades    3   
12 two   spades    2   
13 ace   spades    1   
14 king  clubs    13   
15 queen clubs    12   
16 jack  clubs    11   
17 ten   clubs    10   
18 nine  clubs     9   
19 eight clubs     8   
20 seven clubs     7   
21 six   clubs     6   
22 five  clubs     5   
23 four  clubs     4   
24 three clubs     3   
25 two   clubs     2   
26 ace   clubs     1   
27 king  diamonds 13   
28 queen diamonds 12   
29 jack  diamonds 11   
30 ten   diamonds 10   
31 nine  diamonds  9   
32 eight diamonds  8   
33 seven diamonds  7   
34 six   diamonds  6   
35 five  diamonds  5   
36 four  diamonds  4   
37 three diamonds  3   
38 two   diamonds  2   
39 ace   diamonds  1   
40 king  hearts   13   
41 queen hearts   12   
42 jack  hearts   11   
43 ten   hearts   10   
44 nine  hearts    9   
45 eight hearts    8   
46 seven hearts    7   
47 six   hearts    6   
48 five  hearts    5   
49 four  hearts    4   
50 three hearts    3   
51 two   hearts    2   
52 ace   hearts    1

# 6. R Notation

In [8]:
deal <- function(cards) {
    cards[1,]
}

shuffle <- function(cards) {
    random <- sample(1:52, size=52)
    cards[random, ]
}

In [10]:
deal(deck)

face suit   value
1 king spades 13

In [12]:
deck2 = shuffle(deck)

In [13]:
deck2

face  suit     value
7  seven spades    7   
20 seven clubs     7   
25 two   clubs     2   
14 king  clubs    13   
2  queen spades   12   
5  nine  spades    9   
26 ace   clubs     1   
12 two   spades    2   
10 four  spades    4   
29 jack  diamonds 11   
40 king  hearts   13   
47 six   hearts    6   
1  king  spades   13   
4  ten   spades   10   
43 ten   hearts   10   
52 ace   hearts    1   
3  jack  spades   11   
42 jack  hearts   11   
22 five  clubs     5   
31 nine  diamonds  9   
18 nine  clubs     9   
28 queen diamonds 12   
49 four  hearts    4   
32 eight diamonds  8   
48 five  hearts    5   
9  five  spades    5   
38 two   diamonds  2   
6  eight spades    8   
44 nine  hearts    9   
27 king  diamonds 13   
51 two   hearts    2   
46 seven hearts    7   
8  six   spades    6   
35 five  diamonds  5   
13 ace   spades    1   
41 queen hearts   12   
19 eight clubs     8   
23 four  clubs     4   
36 four  diamonds  4   
11 three spades    3   
15 queen clubs    12   
24 three clubs     3   
30 ten   diamonds 10   
21 six   clubs     6   
45 eight hearts    8   
39 ace   diamonds  1   
16 jack  clubs    11   
34 six   diamonds  6   
50 three hearts    3   
17 ten   clubs    10   
33 seven diamonds  7   
37 three diamonds  3

# 7. Modifying values

In [17]:
vec = 1:6
vec[8] = 1
vec

[1]  1  2  3  4  5  6 NA  1

In [23]:
vec[7] = NA

In [24]:
vec

[1]  1  2  3  4  5  6 NA  1

# 8. Environments

In [28]:
# install.packages("pryr")
library(pryr)
parenvs(all=TRUE)

   label                            name               
1  <environment: R_GlobalEnv>       ""                 
2  <environment: package:pryr>      "package:pryr"     
3  <environment: 0x7f80d36372b0>    "jupyter:irkernel" 
4  <environment: package:stats>     "package:stats"    
5  <environment: package:graphics>  "package:graphics" 
6  <environment: package:grDevices> "package:grDevices"
7  <environment: package:utils>     "package:utils"    
8  <environment: package:datasets>  "package:datasets" 
9  <environment: package:methods>   "package:methods"  
10 <environment: 0x7f80f2aa2198>    "Autoloads"        
11 <environment: base>              ""                 
12 <environment: R_EmptyEnv>        ""                 